package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

type CppCodeGenerator struct {
	descriptor *ProtocolDescriptor
	newLineStr string
}

func NewCppCodeGenerator() *CppCodeGenerator {
	newObj := new(CppCodeGenerator)

	return newObj
}

func (this *CppCodeGenerator) Close() {
	this.descriptor = nil
}

func (this *CppCodeGenerator) Generate(
	descriptor *ProtocolDescriptor,
	outputDir string, newLineType NewLineType) bool {

	this.descriptor = descriptor
	if newLineType == NewLineType_Dos {
		this.newLineStr = "\r\n"
	} else {
		this.newLineStr = "\n"
	}

	headerFilePath := filepath.Join(
		outputDir, this.descriptor.ProtoDef.Name+".h")
	headerFileContent := this.generateHeaderFile()
	if utilWriteAllText(headerFilePath, headerFileContent) == false {
		return false
	}

	sourceFilePath := filepath.Join(
		outputDir, this.descriptor.ProtoDef.Name+".cc")
	sourceFileContent := this.generateSourceFile()
	if utilWriteAllText(sourceFilePath, sourceFileContent) == false {
		return false
	}

	return true
}

// short for write line
func (this *CppCodeGenerator) writeLine(
	sb *strings.Builder, line string) {

	sb.WriteString(line)
	sb.WriteString(this.newLineStr)
}

func (this *CppCodeGenerator) writeLineFormat(
	sb *strings.Builder, format string, args ...any) {

	fmt.Fprintf(sb, format, args...)
	sb.WriteString(this.newLineStr)
}

func (this *CppCodeGenerator) writeEmptyLine(
	sb *strings.Builder) {

	sb.WriteString(this.newLineStr)
}

func (this *CppCodeGenerator) generateHeaderFile() string {
	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeHeaderFileIncludeGuardBegin(&sb)
	this.writeNamespaceDeclStart(&sb)
	this.writeEmptyLine(&sb)
	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CppCodeGenerator) generateSourceFile() string {
	var sb strings.Builder

	this.writeDontEditComment(&sb)

	return sb.String()
}

func (this *CppCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb, "/*")
	this.writeLine(sb, " * Generated by brickred exchange compiler.")
	this.writeLine(sb, " * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb, " */")
}

func (this *CppCodeGenerator) writeNamespaceDeclStart(
	sb *strings.Builder) {

	namespaceDef, ok := this.descriptor.ProtoDef.Namespaces["cpp"]
	if ok == false {
		return
	}

	namespaceName := strings.Join(namespaceDef.NamespaceParts, "::")
	this.writeLineFormat(sb, "namespace %s {", namespaceName)
}

func (this *CppCodeGenerator) writeNamespaceDeclEnd(
	sb *strings.Builder) {

	namespaceDef, ok := this.descriptor.ProtoDef.Namespaces["cpp"]
	if ok == false {
		return
	}

	namespaceName := strings.Join(namespaceDef.NamespaceParts, "::")
	this.writeLineFormat(sb, "} // namespace %s", namespaceName)
}

func (this *CppCodeGenerator) writeHeaderFileIncludeGuardBegin(
	sb *strings.Builder) {

	guardNameParts := make([]string, 0)
	guardNameParts = append(guardNameParts, "BRICKRED_EXCHANGE_GENERATED")

	namespaceDef, ok := this.descriptor.ProtoDef.Namespaces["cpp"]
	if ok {
		guardNameParts = append(
			guardNameParts, namespaceDef.NamespaceParts...)
	}
	guardNameParts = append(guardNameParts,
		g_notWordRegexp.ReplaceAllString(
			this.descriptor.ProtoDef.Name, "_"))
	guardNameParts = append(guardNameParts, "H")

	guardName := strings.ToUpper(strings.Join(guardNameParts, "_"))

	this.writeLineFormat(sb, "#ifndef %s", guardName)
	this.writeLineFormat(sb, "#define %s", guardName)
}
