package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

type CSharpCodeGenerator struct {
	BaseCodeGenerator
}

func NewCSharpCodeGenerator() *CSharpCodeGenerator {
	newObj := new(CSharpCodeGenerator)

	return newObj
}

func (this *CSharpCodeGenerator) Close() {
	this.close()
}

func (this *CSharpCodeGenerator) Generate(
	descriptor *ProtocolDescriptor,
	outputDir string, newLineType NewLineType) bool {

	this.init(descriptor, newLineType)

	sourceFilePath := filepath.Join(
		outputDir, this.descriptor.ProtoDef.Name+".cs")
	sourceFileContent := this.generateSourceFile()
	if utilWriteAllText(sourceFilePath, sourceFileContent) == false {
		return false
	}

	return true
}

func (this *CSharpCodeGenerator) getEnumFullQualifiedName(
	enumDef *EnumDef) string {

	protoDef := enumDef.ParentRef
	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok {
		return fmt.Sprintf(
			"%s.%s",
			namespaceDef.Namespace,
			enumDef.Name)
	} else {
		return enumDef.Name
	}
}

func (this *CSharpCodeGenerator) getEnumItemFullQualifiedName(
	enumItemDef *EnumItemDef) string {

	enumDef := enumItemDef.ParentRef
	protoDef := enumDef.ParentRef
	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok {
		return fmt.Sprintf(
			"%s.%s.%s",
			namespaceDef.Namespace,
			enumDef.Name,
			enumItemDef.Name)
	} else {
		return fmt.Sprintf(
			"%s.%s",
			enumDef.Name,
			enumItemDef.Name)
	}
}

func (this *CSharpCodeGenerator) getStructFullQualifiedName(
	structDef *StructDef) string {

	protoDef := structDef.ParentRef
	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok {
		return fmt.Sprintf(
			"%s.%s",
			namespaceDef.Namespace,
			structDef.Name)
	} else {
		return structDef.Name
	}
}

func (this *CSharpCodeGenerator) getStructFieldCSharpType(
	fieldDef *StructFieldDef) string {

	var checkType StructFieldType
	if fieldDef.Type == StructFieldType_List {
		checkType = fieldDef.ListType
	} else {
		checkType = fieldDef.Type
	}

	csharpType := ""
	if checkType == StructFieldType_I8 {
		csharpType = "sbyte"
	} else if checkType == StructFieldType_U8 {
		csharpType = "byte"
	} else if checkType == StructFieldType_I16 ||
		checkType == StructFieldType_I16V {
		csharpType = "short"
	} else if checkType == StructFieldType_U16 ||
		checkType == StructFieldType_U16V {
		csharpType = "ushort"
	} else if checkType == StructFieldType_I32 ||
		checkType == StructFieldType_I32V {
		csharpType = "int"
	} else if checkType == StructFieldType_U32 ||
		checkType == StructFieldType_U32V {
		csharpType = "uint"
	} else if checkType == StructFieldType_I64 ||
		checkType == StructFieldType_I64V {
		csharpType = "long"
	} else if checkType == StructFieldType_U64 ||
		checkType == StructFieldType_U64V {
		csharpType = "ulong"
	} else if checkType == StructFieldType_String {
		csharpType = "string"
	} else if checkType == StructFieldType_Bytes {
		csharpType = "byte[]"
	} else if checkType == StructFieldType_Bool {
		csharpType = "bool"
	} else if checkType == StructFieldType_Enum {
		csharpType = this.getEnumFullQualifiedName(fieldDef.RefEnumDef)
	} else if checkType == StructFieldType_Struct {
		csharpType = this.getStructFullQualifiedName(fieldDef.RefStructDef)
	}

	if fieldDef.Type == StructFieldType_List {
		return fmt.Sprintf("List<%s>", csharpType)
	} else {
		return csharpType
	}
}

func (this *CSharpCodeGenerator) getStructFieldCSharpTypeDefaultValue(
	fieldDef *StructFieldDef) string {

	checkType := fieldDef.Type

	if StructFieldTypeIsInteger(checkType) {
		return "0"
	} else if checkType == StructFieldType_String {
		return "\"\""
	} else if checkType == StructFieldType_Bytes {
		return "new byte[0]"
	} else if checkType == StructFieldType_Bool {
		return "false"
	} else if checkType == StructFieldType_Enum {
		if len(fieldDef.RefEnumDef.Items) > 0 {
			return this.getEnumItemFullQualifiedName(
				fieldDef.RefEnumDef.Items[0])
		} else {
			return fmt.Sprintf("(%s)0",
				this.getEnumFullQualifiedName(fieldDef.RefEnumDef))
		}
	} else if checkType == StructFieldType_Struct {
		return fmt.Sprintf("new %s()",
			this.getStructFullQualifiedName(fieldDef.RefStructDef))
	} else if checkType == StructFieldType_List {
		return fmt.Sprintf("new %s()",
			this.getStructFieldCSharpType(fieldDef))
	} else {
		return ""
	}
}

func (this *CSharpCodeGenerator) generateSourceFile() string {
	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeUseStatementsDecl(&sb)
	this.writeNamespaceDeclStart(&sb)

	isFirstDecl := true
	indent := this.getIndent()
	this.writeEnumDecl(&sb, &isFirstDecl, indent)
	this.writeStructDecl(&sb, &isFirstDecl, indent)

	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CSharpCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb,
		"/*")
	this.writeLine(sb,
		" * Generated by brickred exchange compiler.")
	this.writeLine(sb,
		" * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb,
		" */")
}

func (this *CSharpCodeGenerator) getIndent() string {
	protoDef := this.descriptor.ProtoDef

	if _, ok := protoDef.Namespaces["csharp"]; ok {
		return "    "
	} else {
		return ""
	}
}

func (this *CSharpCodeGenerator) writeUseStatementsDecl(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	useBrickredExchange := false
	useSystem := false
	useSystemCollectionsGeneric := false

	if len(protoDef.Structs) > 0 ||
		len(protoDef.EnumMaps) > 0 {
		useBrickredExchange = true
	}
	if len(protoDef.EnumMaps) > 0 {
		useSystem = true
	}

	for _, structDef := range protoDef.Structs {
		if len(structDef.Fields) > 0 {
			useSystemCollectionsGeneric = true
		}
		for _, def := range structDef.Fields {
			if def.Type == StructFieldType_Bytes ||
				def.ListType == StructFieldType_Bytes {
				// for BitConverter
				useSystem = true
			}
		}
	}

	if useSystem == false &&
		useSystemCollectionsGeneric == false &&
		useBrickredExchange == false {
		return
	}

	this.writeEmptyLine(sb)
	if useBrickredExchange {
		this.writeLine(sb,
			"using Brickred.Exchange;")
	}
	if useSystem {
		this.writeLine(sb,
			"using System;")
	}
	if useSystemCollectionsGeneric {
		this.writeLine(sb,
			"using System.Collections.Generic;")
	}
}

func (this *CSharpCodeGenerator) writeNamespaceDeclStart(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok == false {
		return
	}

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"namespace %s",
		namespaceDef.Namespace)
	this.writeLine(sb,
		"{")
}

func (this *CSharpCodeGenerator) writeNamespaceDeclEnd(
	sb *strings.Builder) {

	this.writeLine(sb,
		"}")
}

func (this *CSharpCodeGenerator) writeEnumDecl(
	sb *strings.Builder, isFirstDecl *bool, indent string) {

	protoDef := this.descriptor.ProtoDef

	for _, def := range protoDef.Enums {
		this.writeOneEnumDecl(sb, def, isFirstDecl, indent)
	}
}

func (this *CSharpCodeGenerator) writeOneEnumDecl(
	sb *strings.Builder, enumDef *EnumDef, isFirstDecl *bool, indent string) {

	if *isFirstDecl == true {
		*isFirstDecl = false
	} else {
		this.writeEmptyLine(sb)
	}

	this.writeLineFormat(sb,
		"%spublic enum %s",
		indent, enumDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)

	for _, def := range enumDef.Items {
		if def.Type == EnumItemType_Default {
			this.writeLineFormat(sb,
				"%s    %s,",
				indent, def.Name)
		} else if def.Type == EnumItemType_Int {
			this.writeLineFormat(sb,
				"%s    %s = %d,",
				indent, def.Name, def.IntValue)
		} else if def.Type == EnumItemType_CurrentEnumRef {
			this.writeLineFormat(sb,
				"%s    %s = %s,",
				indent, def.Name, def.RefEnumItemDef.Name)
		} else if def.Type == EnumItemType_OtherEnumRef {
			this.writeLineFormat(sb,
				"%s    %s = %s,",
				indent, def.Name,
				this.getEnumItemFullQualifiedName(def.RefEnumItemDef))
		}
	}

	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeStructDecl(
	sb *strings.Builder, isFirstDecl *bool, indent string) {

	protoDef := this.descriptor.ProtoDef

	for _, def := range protoDef.Structs {
		this.writeOneStructDecl(sb, def, isFirstDecl, indent)
	}
}

func (this *CSharpCodeGenerator) writeOneStructDecl(
	sb *strings.Builder, structDef *StructDef, isFirstDecl *bool, indent string) {

	if *isFirstDecl == true {
		*isFirstDecl = false
	} else {
		this.writeEmptyLine(sb)
	}

	this.writeLineFormat(sb,
		"%spublic sealed class %s : BaseStruct",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)
	this.writeOneStructDeclFieldDecl(sb, structDef, indent)
	this.writeOneStructDeclCreateFunc(sb, structDef, indent)
	this.writeOneStructDeclConstructor(sb, structDef, indent)
	this.writeOneStructDeclCopyConstructor(sb, structDef, indent)
	this.writeOneStructDeclCloneFunc(sb, structDef, indent)
	this.writeOneStructDeclEncodeToStreamFunc(sb, structDef, indent)
	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclFieldDecl(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if structDef.OptionalByteCount > 0 {
		this.writeLineFormat(sb,
			"%s    private byte[] _has_bits_ = new byte[%d];",
			indent, structDef.OptionalByteCount)
	}

	for _, def := range structDef.Fields {
		this.writeLineFormat(sb,
			"%s    public %s %s = %s;",
			indent,
			this.getStructFieldCSharpType(def),
			def.Name,
			this.getStructFieldCSharpTypeDefaultValue(def))
	}
}

func (this *CSharpCodeGenerator) writeOneStructDeclCreateFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if len(structDef.Fields) > 0 {
		this.writeEmptyLine(sb)
	}
	this.writeLineFormat(sb,
		"%s    public static %s Create()",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return new %s();",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclConstructor(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public %s()",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclCopyConstructor(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public %s(%s other)",
		indent, structDef.Name, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	if structDef.OptionalFieldCount > 0 {
		this.writeLineFormat(sb, ""+
			"%s        "+
			"this._has_bits_ = other._has_bits_.Clone() as byte[];",
			indent)
	}

	for _, def := range structDef.Fields {
		checkType := def.Type

		if StructFieldTypeIsInteger(checkType) ||
			checkType == StructFieldType_String ||
			checkType == StructFieldType_Bool ||
			checkType == StructFieldType_Enum {
			this.writeLineFormat(sb,
				"%s        this.%s = other.%s;",
				indent, def.Name, def.Name)
		} else if checkType == StructFieldType_Bytes {
			this.writeLineFormat(sb,
				"%s        this.%s = other.%s.Clone() as byte[];",
				indent, def.Name, def.Name)
		} else if checkType == StructFieldType_Struct {
			this.writeLineFormat(sb,
				"%s        this.%s = new %s(other.%s);",
				indent, def.Name,
				this.getStructFullQualifiedName(def.RefStructDef),
				def.Name)
		} else if checkType == StructFieldType_List {
			checkType = def.ListType

			if StructFieldTypeIsInteger(checkType) ||
				checkType == StructFieldType_String ||
				checkType == StructFieldType_Bool ||
				checkType == StructFieldType_Enum {
				this.writeLineFormat(sb,
					"%s        this.%s = new %s(other.%s);",
					indent, def.Name,
					this.getStructFieldCSharpType(def),
					def.Name)
			} else if checkType == StructFieldType_Bytes {
				this.writeLineFormat(sb,
					"%s        this.%s = other.%s.ConvertAll(o => o.Clone() as byte[]);",
					indent, def.Name, def.Name)
			} else if checkType == StructFieldType_Struct {
				this.writeLineFormat(sb,
					"%s        this.%s = other.%s.ConvertAll(o => new %s(o));",
					indent, def.Name, def.Name,
					this.getStructFullQualifiedName(def.RefStructDef))
			}
		}
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclCloneFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    new public %s Clone()",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return (%s)CloneInternal();",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    }",
		indent)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    protected override BaseStruct CloneInternal()",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return new %s(this);",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclEncodeToStreamFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
}
