package main

import (
	"path/filepath"
	"strings"
)

type CSharpCodeGenerator struct {
	BaseCodeGenerator
}

func NewCSharpCodeGenerator() *CSharpCodeGenerator {
	newObj := new(CSharpCodeGenerator)

	return newObj
}

func (this *CSharpCodeGenerator) Close() {
	this.close()
}

func (this *CSharpCodeGenerator) Generate(
	descriptor *ProtocolDescriptor,
	outputDir string, newLineType NewLineType) bool {

	this.init(descriptor, newLineType)

	sourceFilePath := filepath.Join(
		outputDir, this.descriptor.ProtoDef.Name+".cs")
	sourceFileContent := this.generateSourceFile()
	if utilWriteAllText(sourceFilePath, sourceFileContent) == false {
		return false
	}

	return true
}

func (this *CSharpCodeGenerator) generateSourceFile() string {
	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeUseStatementsDecl(&sb)

	return sb.String()
}

func (this *CSharpCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb,
		"/*")
	this.writeLine(sb,
		" * Generated by brickred exchange compiler.")
	this.writeLine(sb,
		" * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb,
		" */")
}

func (this *CSharpCodeGenerator) writeUseStatementsDecl(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	useBrickredExchange := false
	useSystem := false
	useSystemCollectionsGeneric := false

	if len(protoDef.Structs) > 0 ||
		len(protoDef.EnumMaps) > 0 {
		useBrickredExchange = true
	}
	if len(protoDef.EnumMaps) > 0 {
		useSystem = true
	}

	for _, structDef := range protoDef.Structs {
		if len(structDef.Fields) > 0 {
			useSystemCollectionsGeneric = true
		}
		for _, def := range structDef.Fields {
			if def.Type == StructFieldType_Bytes ||
				def.ListType == StructFieldType_Bytes {
				// for BitConverter
				useSystem = true
			}
		}
	}

	if useSystem == false &&
		useSystemCollectionsGeneric == false &&
		useBrickredExchange == false {
		return
	}

	this.writeEmptyLine(sb)
	if useBrickredExchange {
		this.writeLine(sb,
			"using Brickred.Exchange;")
	}
	if useSystem {
		this.writeLine(sb,
			"using System;")
	}
	if useSystemCollectionsGeneric {
		this.writeLine(sb,
			"using System.Collections.Generic;")
	}
}
