package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

type CSharpCodeGenerator struct {
	BaseCodeGenerator
}

func NewCSharpCodeGenerator() *CSharpCodeGenerator {
	newObj := new(CSharpCodeGenerator)

	return newObj
}

func (this *CSharpCodeGenerator) Close() {
	this.close()
}

func (this *CSharpCodeGenerator) Generate(
	descriptor *ProtocolDescriptor,
	outputDir string, newLineType NewLineType) bool {

	this.init(descriptor, newLineType)

	sourceFilePath := filepath.Join(
		outputDir, this.descriptor.ProtoDef.Name+".cs")
	sourceFileContent := this.generateSourceFile()
	if utilWriteAllText(sourceFilePath, sourceFileContent) == false {
		return false
	}

	return true
}

func (this *CSharpCodeGenerator) getEnumFullQualifiedName(
	enumDef *EnumDef) string {

	protoDef := enumDef.ParentRef
	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok {
		return fmt.Sprintf(
			"%s.%s",
			namespaceDef.Namespace,
			enumDef.Name)
	} else {
		return enumDef.Name
	}
}

func (this *CSharpCodeGenerator) getEnumItemFullQualifiedName(
	enumItemDef *EnumItemDef) string {

	enumDef := enumItemDef.ParentRef
	protoDef := enumDef.ParentRef
	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok {
		return fmt.Sprintf(
			"%s.%s.%s",
			namespaceDef.Namespace,
			enumDef.Name,
			enumItemDef.Name)
	} else {
		return fmt.Sprintf(
			"%s.%s",
			enumDef.Name,
			enumItemDef.Name)
	}
}

func (this *CSharpCodeGenerator) getStructFullQualifiedName(
	structDef *StructDef) string {

	protoDef := structDef.ParentRef
	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok {
		return fmt.Sprintf(
			"%s.%s",
			namespaceDef.Namespace,
			structDef.Name)
	} else {
		return structDef.Name
	}
}

func (this *CSharpCodeGenerator) getStructFieldCSharpType(
	fieldDef *StructFieldDef) string {

	var checkType StructFieldType
	if fieldDef.Type == StructFieldType_List {
		checkType = fieldDef.ListType
	} else {
		checkType = fieldDef.Type
	}

	csharpType := ""
	if checkType == StructFieldType_I8 {
		csharpType = "sbyte"
	} else if checkType == StructFieldType_U8 {
		csharpType = "byte"
	} else if checkType == StructFieldType_I16 ||
		checkType == StructFieldType_I16V {
		csharpType = "short"
	} else if checkType == StructFieldType_U16 ||
		checkType == StructFieldType_U16V {
		csharpType = "ushort"
	} else if checkType == StructFieldType_I32 ||
		checkType == StructFieldType_I32V {
		csharpType = "int"
	} else if checkType == StructFieldType_U32 ||
		checkType == StructFieldType_U32V {
		csharpType = "uint"
	} else if checkType == StructFieldType_I64 ||
		checkType == StructFieldType_I64V {
		csharpType = "long"
	} else if checkType == StructFieldType_U64 ||
		checkType == StructFieldType_U64V {
		csharpType = "ulong"
	} else if checkType == StructFieldType_String {
		csharpType = "string"
	} else if checkType == StructFieldType_Bytes {
		csharpType = "byte[]"
	} else if checkType == StructFieldType_Bool {
		csharpType = "bool"
	} else if checkType == StructFieldType_Enum {
		csharpType = this.getEnumFullQualifiedName(fieldDef.RefEnumDef)
	} else if checkType == StructFieldType_Struct {
		csharpType = this.getStructFullQualifiedName(fieldDef.RefStructDef)
	}

	if fieldDef.Type == StructFieldType_List {
		return fmt.Sprintf("List<%s>", csharpType)
	} else {
		return csharpType
	}
}

func (this *CSharpCodeGenerator) getStructFieldCSharpTypeDefaultValue(
	fieldDef *StructFieldDef) string {

	checkType := fieldDef.Type

	if StructFieldTypeIsInteger(checkType) {
		return "0"
	} else if checkType == StructFieldType_String {
		return "\"\""
	} else if checkType == StructFieldType_Bytes {
		return "new byte[0]"
	} else if checkType == StructFieldType_Bool {
		return "false"
	} else if checkType == StructFieldType_Enum {
		if len(fieldDef.RefEnumDef.Items) > 0 {
			return this.getEnumItemFullQualifiedName(
				fieldDef.RefEnumDef.Items[0])
		} else {
			return fmt.Sprintf("(%s)0",
				this.getEnumFullQualifiedName(fieldDef.RefEnumDef))
		}
	} else if checkType == StructFieldType_Struct {
		return fmt.Sprintf("new %s()",
			this.getStructFullQualifiedName(fieldDef.RefStructDef))
	} else if checkType == StructFieldType_List {
		return fmt.Sprintf("new %s()",
			this.getStructFieldCSharpType(fieldDef))
	} else {
		return ""
	}
}

func (this *CSharpCodeGenerator) generateSourceFile() string {
	var sb strings.Builder

	this.writeDontEditComment(&sb)
	this.writeUseStatementsDecl(&sb)
	this.writeNamespaceDeclStart(&sb)

	isFirstDecl := true
	indent := this.getIndent()
	this.writeEnumDecl(&sb, &isFirstDecl, indent)
	this.writeStructDecl(&sb, &isFirstDecl, indent)
	this.writeEnumMapDecl(&sb, &isFirstDecl, indent)

	this.writeNamespaceDeclEnd(&sb)

	return sb.String()
}

func (this *CSharpCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb,
		"/*")
	this.writeLine(sb,
		" * Generated by brickred exchange compiler.")
	this.writeLine(sb,
		" * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb,
		" */")
}

func (this *CSharpCodeGenerator) getIndent() string {
	protoDef := this.descriptor.ProtoDef

	if _, ok := protoDef.Namespaces["csharp"]; ok {
		return "    "
	} else {
		return ""
	}
}

func (this *CSharpCodeGenerator) writeUseStatementsDecl(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	useBrickredExchange := false
	useSystem := false
	useSystemCollectionsGeneric := false

	if len(protoDef.Structs) > 0 ||
		len(protoDef.EnumMaps) > 0 {
		useBrickredExchange = true
	}
	if len(protoDef.EnumMaps) > 0 {
		useSystem = true
	}

	for _, structDef := range protoDef.Structs {
		if len(structDef.Fields) > 0 {
			useSystemCollectionsGeneric = true
		}
		for _, def := range structDef.Fields {
			if def.Type == StructFieldType_Bytes ||
				def.ListType == StructFieldType_Bytes {
				// for BitConverter
				useSystem = true
			}
		}
	}

	if useSystem == false &&
		useSystemCollectionsGeneric == false &&
		useBrickredExchange == false {
		return
	}

	this.writeEmptyLine(sb)
	if useBrickredExchange {
		this.writeLine(sb,
			"using Brickred.Exchange;")
	}
	if useSystem {
		this.writeLine(sb,
			"using System;")
	}
	if useSystemCollectionsGeneric {
		this.writeLine(sb,
			"using System.Collections.Generic;")
	}
}

func (this *CSharpCodeGenerator) writeNamespaceDeclStart(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	namespaceDef, ok := protoDef.Namespaces["csharp"]
	if ok == false {
		this.writeEmptyLine(sb)
		return
	}

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"namespace %s",
		namespaceDef.Namespace)
	this.writeLine(sb,
		"{")
}

func (this *CSharpCodeGenerator) writeNamespaceDeclEnd(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	_, ok := protoDef.Namespaces["csharp"]
	if ok == false {
		return
	}

	this.writeLine(sb,
		"}")
}

func (this *CSharpCodeGenerator) writeEnumDecl(
	sb *strings.Builder, isFirstDecl *bool, indent string) {

	protoDef := this.descriptor.ProtoDef

	for _, def := range protoDef.Enums {
		this.writeOneEnumDecl(sb, def, isFirstDecl, indent)
	}
}

func (this *CSharpCodeGenerator) writeOneEnumDecl(
	sb *strings.Builder, enumDef *EnumDef,
	isFirstDecl *bool, indent string) {

	if *isFirstDecl == true {
		*isFirstDecl = false
	} else {
		this.writeEmptyLine(sb)
	}

	this.writeLineFormat(sb,
		"%spublic enum %s",
		indent, enumDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)

	for _, def := range enumDef.Items {
		if def.Type == EnumItemType_Default {
			this.writeLineFormat(sb,
				"%s    %s,",
				indent, def.Name)
		} else if def.Type == EnumItemType_Int {
			this.writeLineFormat(sb,
				"%s    %s = %d,",
				indent, def.Name, def.IntValue)
		} else if def.Type == EnumItemType_CurrentEnumRef {
			this.writeLineFormat(sb,
				"%s    %s = %s,",
				indent, def.Name, def.RefEnumItemDef.Name)
		} else if def.Type == EnumItemType_OtherEnumRef {
			this.writeLineFormat(sb,
				"%s    %s = %s,",
				indent, def.Name,
				this.getEnumItemFullQualifiedName(def.RefEnumItemDef))
		}
	}

	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeStructDecl(
	sb *strings.Builder, isFirstDecl *bool, indent string) {

	protoDef := this.descriptor.ProtoDef

	for _, def := range protoDef.Structs {
		this.writeOneStructDecl(sb, def, isFirstDecl, indent)
	}
}

func (this *CSharpCodeGenerator) writeOneStructDecl(
	sb *strings.Builder, structDef *StructDef,
	isFirstDecl *bool, indent string) {

	if *isFirstDecl == true {
		*isFirstDecl = false
	} else {
		this.writeEmptyLine(sb)
	}

	this.writeLineFormat(sb,
		"%spublic sealed class %s : BaseStruct",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)
	this.writeOneStructDeclFieldDecl(sb, structDef, indent)
	this.writeOneStructDeclCreateFunc(sb, structDef, indent)
	this.writeOneStructDeclConstructor(sb, structDef, indent)
	this.writeOneStructDeclCopyConstructor(sb, structDef, indent)
	this.writeOneStructDeclCloneFunc(sb, structDef, indent)
	this.writeOneStructDeclEncodeToStreamFunc(sb, structDef, indent)
	this.writeOneStructDeclDecodeFromStreamFunc(sb, structDef, indent)
	this.writeOneStructDeclDumpFunc(sb, structDef, indent)
	this.writeOneStructDeclOptionalFunc(sb, structDef, indent)
	this.writeLineFormat(sb,
		"%s}",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclFieldDecl(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if structDef.OptionalByteCount > 0 {
		this.writeLineFormat(sb,
			"%s    private byte[] _has_bits_ = new byte[%d];",
			indent, structDef.OptionalByteCount)
	}

	for _, def := range structDef.Fields {
		this.writeLineFormat(sb,
			"%s    public %s %s = %s;",
			indent,
			this.getStructFieldCSharpType(def),
			def.Name,
			this.getStructFieldCSharpTypeDefaultValue(def))
	}
}

func (this *CSharpCodeGenerator) writeOneStructDeclCreateFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if len(structDef.Fields) > 0 {
		this.writeEmptyLine(sb)
	}
	this.writeLineFormat(sb,
		"%s    public static %s Create()",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return new %s();",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclConstructor(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public %s()",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclCopyConstructor(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public %s(%s other)",
		indent, structDef.Name, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	if structDef.OptionalFieldCount > 0 {
		this.writeLineFormat(sb, ""+
			"%s        "+
			"this._has_bits_ = other._has_bits_.Clone() as byte[];",
			indent)
	}

	for _, def := range structDef.Fields {
		checkType := def.Type

		if StructFieldTypeIsInteger(checkType) ||
			checkType == StructFieldType_String ||
			checkType == StructFieldType_Bool ||
			checkType == StructFieldType_Enum {
			this.writeLineFormat(sb,
				"%s        this.%s = other.%s;",
				indent, def.Name, def.Name)
		} else if checkType == StructFieldType_Bytes {
			this.writeLineFormat(sb,
				"%s        this.%s = other.%s.Clone() as byte[];",
				indent, def.Name, def.Name)
		} else if checkType == StructFieldType_Struct {
			this.writeLineFormat(sb,
				"%s        this.%s = new %s(other.%s);",
				indent, def.Name,
				this.getStructFullQualifiedName(def.RefStructDef),
				def.Name)
		} else if checkType == StructFieldType_List {
			checkType = def.ListType

			if StructFieldTypeIsInteger(checkType) ||
				checkType == StructFieldType_String ||
				checkType == StructFieldType_Bool ||
				checkType == StructFieldType_Enum {
				this.writeLineFormat(sb,
					"%s        this.%s = new %s(other.%s);",
					indent, def.Name,
					this.getStructFieldCSharpType(def),
					def.Name)
			} else if checkType == StructFieldType_Bytes {
				this.writeLineFormat(sb,
					"%s        this.%s = other.%s.ConvertAll(o => o.Clone() as byte[]);",
					indent, def.Name, def.Name)
			} else if checkType == StructFieldType_Struct {
				this.writeLineFormat(sb,
					"%s        this.%s = other.%s.ConvertAll(o => new %s(o));",
					indent, def.Name, def.Name,
					this.getStructFullQualifiedName(def.RefStructDef))
			}
		}
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclCloneFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    new public %s Clone()",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return (%s)CloneInternal();",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    }",
		indent)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    protected override BaseStruct CloneInternal()",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return new %s(this);",
		indent, structDef.Name)
	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclEncodeToStreamFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public override void EncodeToStream(CodecOutputStream s)",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	if structDef.OptionalByteCount > 0 {
		this.writeLineFormat(sb,
			"%s        for (int i = 0; i < %d; ++i) {",
			indent, structDef.OptionalByteCount)
		this.writeLineFormat(sb,
			"%s            s.WriteUInt8(this._has_bits_[i]);",
			indent)
		this.writeLineFormat(sb,
			"%s        }",
			indent)
		this.writeEmptyLine(sb)
	}

	for _, def := range structDef.Fields {
		this.writeOneStructDeclEncodeToStreamFuncWriteStatement(
			sb, def, indent)
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclEncodeToStreamFuncWriteStatement(
	sb *strings.Builder, fieldDef *StructFieldDef, indent string) {

	if fieldDef.IsOptional {
		this.writeLineFormat(sb,
			"%s        if (has_%s()) {",
			indent, fieldDef.Name)
	}

	isList := fieldDef.Type == StructFieldType_List
	var checkType StructFieldType
	if fieldDef.Type == StructFieldType_List {
		checkType = fieldDef.ListType
	} else {
		checkType = fieldDef.Type
	}

	var writeFunc string
	if checkType == StructFieldType_I8 {
		writeFunc = "WriteInt8"
	} else if checkType == StructFieldType_U8 {
		writeFunc = "WriteUInt8"
	} else if checkType == StructFieldType_I16 {
		writeFunc = "WriteInt16"
	} else if checkType == StructFieldType_U16 {
		writeFunc = "WriteUInt16"
	} else if checkType == StructFieldType_I32 {
		writeFunc = "WriteInt32"
	} else if checkType == StructFieldType_U32 {
		writeFunc = "WriteUInt32"
	} else if checkType == StructFieldType_I64 {
		writeFunc = "WriteInt64"
	} else if checkType == StructFieldType_U64 {
		writeFunc = "WriteUInt64"
	} else if checkType == StructFieldType_I16V {
		writeFunc = "WriteInt16V"
	} else if checkType == StructFieldType_U16V {
		writeFunc = "WriteUInt16V"
	} else if checkType == StructFieldType_I32V {
		writeFunc = "WriteInt32V"
	} else if checkType == StructFieldType_U32V {
		writeFunc = "WriteUInt32V"
	} else if checkType == StructFieldType_I64V {
		writeFunc = "WriteInt64V"
	} else if checkType == StructFieldType_U64V {
		writeFunc = "WriteUInt64V"
	} else if checkType == StructFieldType_String {
		writeFunc = "WriteString"
	} else if checkType == StructFieldType_Bytes {
		writeFunc = "WriteBytes"
	} else if checkType == StructFieldType_Bool {
		writeFunc = "WriteBool"
	} else {
		writeFunc = ""
	}

	var indent2 string
	if fieldDef.IsOptional {
		indent2 = "            "
	} else {
		indent2 = "        "
	}
	if isList {
		this.writeLineFormat(sb,
			"%s%ss.WriteLength(this.%s.Count);",
			indent, indent2, fieldDef.Name)
		this.writeLineFormat(sb,
			"%s%sfor (int i = 0; i < this.%s.Count; ++i) {",
			indent, indent2, fieldDef.Name)

		if checkType == StructFieldType_Enum {
			this.writeLineFormat(sb,
				"%s%s    s.WriteInt32V((int)this.%s[i]);",
				indent, indent2, fieldDef.Name)
		} else if checkType == StructFieldType_Struct {
			this.writeLineFormat(sb,
				"%s%s    this.%s[i].EncodeToStream(s);",
				indent, indent2, fieldDef.Name)
		} else {
			this.writeLineFormat(sb,
				"%s%s    s.%s(this.%s[i]);",
				indent, indent2, writeFunc, fieldDef.Name)
		}

		this.writeLineFormat(sb,
			"%s%s}",
			indent, indent2)
	} else {
		if checkType == StructFieldType_Enum {
			this.writeLineFormat(sb,
				"%s%ss.WriteInt32V((int)this.%s);",
				indent, indent2, fieldDef.Name)
		} else if checkType == StructFieldType_Struct {
			this.writeLineFormat(sb,
				"%s%sthis.%s.EncodeToStream(s);",
				indent, indent2, fieldDef.Name)
		} else {
			this.writeLineFormat(sb,
				"%s%ss.%s(this.%s);",
				indent, indent2, writeFunc, fieldDef.Name)
		}
	}

	if fieldDef.IsOptional {
		this.writeLineFormat(sb,
			"%s        }",
			indent)
	}
}

func (this *CSharpCodeGenerator) writeOneStructDeclDecodeFromStreamFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public override void DecodeFromStream(CodecInputStream s)",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	if structDef.OptionalByteCount > 0 {
		this.writeLineFormat(sb,
			"%s        for (int i = 0; i < %d; ++i) {",
			indent, structDef.OptionalByteCount)
		this.writeLineFormat(sb,
			"%s            this._has_bits_[i] = s.ReadUInt8();",
			indent)
		this.writeLineFormat(sb,
			"%s        }",
			indent)
		this.writeEmptyLine(sb)
	}

	for _, def := range structDef.Fields {
		this.writeOneStructDeclDecodeFromStreamFuncReadStatement(
			sb, def, indent)
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclDecodeFromStreamFuncReadStatement(
	sb *strings.Builder, fieldDef *StructFieldDef, indent string) {

	if fieldDef.IsOptional {
		this.writeLineFormat(sb,
			"%s        if (has_%s()) {",
			indent, fieldDef.Name)
	}

	isList := fieldDef.Type == StructFieldType_List
	var checkType StructFieldType
	if fieldDef.Type == StructFieldType_List {
		checkType = fieldDef.ListType
	} else {
		checkType = fieldDef.Type
	}

	var readFunc string
	if checkType == StructFieldType_I8 {
		readFunc = "ReadInt8"
	} else if checkType == StructFieldType_U8 {
		readFunc = "ReadUInt8"
	} else if checkType == StructFieldType_I16 {
		readFunc = "ReadInt16"
	} else if checkType == StructFieldType_U16 {
		readFunc = "ReadUInt16"
	} else if checkType == StructFieldType_I32 {
		readFunc = "ReadInt32"
	} else if checkType == StructFieldType_U32 {
		readFunc = "ReadUInt32"
	} else if checkType == StructFieldType_I64 {
		readFunc = "ReadInt64"
	} else if checkType == StructFieldType_U64 {
		readFunc = "ReadUInt64"
	} else if checkType == StructFieldType_I16V {
		readFunc = "ReadInt16V"
	} else if checkType == StructFieldType_U16V {
		readFunc = "ReadUInt16V"
	} else if checkType == StructFieldType_I32V {
		readFunc = "ReadInt32V"
	} else if checkType == StructFieldType_U32V {
		readFunc = "ReadUInt32V"
	} else if checkType == StructFieldType_I64V {
		readFunc = "ReadInt64V"
	} else if checkType == StructFieldType_U64V {
		readFunc = "ReadUInt64V"
	} else if checkType == StructFieldType_String {
		readFunc = "ReadString"
	} else if checkType == StructFieldType_Bytes {
		readFunc = "ReadBytes"
	} else if checkType == StructFieldType_Bool {
		readFunc = "ReadBool"
	} else {
		readFunc = ""
	}

	var indent2 string
	if fieldDef.IsOptional {
		indent2 = "            "
	} else {
		indent2 = "        "
	}
	if isList {
		var indent3 string
		if fieldDef.IsOptional == false {
			indent3 = "    "
		} else {
			indent3 = ""
		}
		if fieldDef.IsOptional == false {
			this.writeLineFormat(sb,
				"%s%s{",
				indent, indent2)
		}
		this.writeLineFormat(sb,
			"%s%s%sint length = s.ReadLength();",
			indent, indent2, indent3)
		this.writeLineFormat(sb,
			"%s%s%sthis.%s.Clear();",
			indent, indent2, indent3, fieldDef.Name)
		this.writeLineFormat(sb,
			"%s%s%sfor (int i = 0; i < length; ++i) {",
			indent, indent2, indent3)

		if checkType == StructFieldType_Enum {
			this.writeLineFormat(sb,
				"%s%s%s    this.%s.Add((%s)s.ReadInt32V());",
				indent, indent2, indent3, fieldDef.Name,
				this.getEnumFullQualifiedName(fieldDef.RefEnumDef))
		} else if checkType == StructFieldType_Struct {
			this.writeLineFormat(sb,
				"%s%s%s    this.%s.Add(s.ReadStruct<%s>());",
				indent, indent2, indent3, fieldDef.Name,
				this.getStructFullQualifiedName(fieldDef.RefStructDef))
		} else {
			this.writeLineFormat(sb,
				"%s%s%s    this.%s.Add(s.%s());",
				indent, indent2, indent3, fieldDef.Name, readFunc)
		}

		this.writeLineFormat(sb,
			"%s%s%s}",
			indent, indent2, indent3)
		if fieldDef.IsOptional == false {
			this.writeLineFormat(sb,
				"%s%s}",
				indent, indent2)
		}
	} else {
		if checkType == StructFieldType_Enum {
			this.writeLineFormat(sb,
				"%s%sthis.%s = (%s)s.ReadInt32V();",
				indent, indent2, fieldDef.Name,
				this.getEnumFullQualifiedName(fieldDef.RefEnumDef))
		} else if checkType == StructFieldType_Struct {
			this.writeLineFormat(sb,
				"%s%sthis.%s = s.ReadStruct<%s>();",
				indent, indent2, fieldDef.Name,
				this.getStructFullQualifiedName(fieldDef.RefStructDef))
		} else {
			this.writeLineFormat(sb,
				"%s%sthis.%s = s.%s();",
				indent, indent2, fieldDef.Name, readFunc)
		}
	}

	if fieldDef.IsOptional {
		this.writeLineFormat(sb,
			"%s        }",
			indent)
	}
}

func (this *CSharpCodeGenerator) writeOneStructDeclDumpFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public override string Dump()",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)

	if len(structDef.Fields) <= 0 {
		this.writeLineFormat(sb,
			"%s        return \"\";",
			indent)
	} else {
		this.writeLineFormat(sb,
			"%s        List<string> sb = new List<string>();",
			indent)
		this.writeEmptyLine(sb)

		for _, def := range structDef.Fields {
			this.writeOneStructDeclDumpFuncWriteStatement(sb, def, indent)
		}

		this.writeEmptyLine(sb)
		this.writeLineFormat(sb,
			"%s        return string.Join(\" \", sb.ToArray());",
			indent)
	}

	this.writeLineFormat(sb,
		"%s    }",
		indent)
}

func (this *CSharpCodeGenerator) writeOneStructDeclDumpFuncWriteStatement(
	sb *strings.Builder, fieldDef *StructFieldDef, indent string) {

	if fieldDef.IsOptional {
		this.writeLineFormat(sb,
			"%s        if (has_%s()) {",
			indent, fieldDef.Name)
	}

	isList := fieldDef.Type == StructFieldType_List
	var checkType StructFieldType
	if fieldDef.Type == StructFieldType_List {
		checkType = fieldDef.ListType
	} else {
		checkType = fieldDef.Type
	}

	var writeStatement string
	if StructFieldTypeIsInteger(checkType) {
		if isList {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {0}\", this.%s[i]))",
				fieldDef.Name, fieldDef.Name)
		} else {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {0}\", this.%s))",
				fieldDef.Name, fieldDef.Name)
		}
	} else if checkType == StructFieldType_String {
		if isList {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: \\\"{0}\\\"\", this.%s[i]))",
				fieldDef.Name, fieldDef.Name)
		} else {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: \\\"{0}\\\"\", this.%s))",
				fieldDef.Name, fieldDef.Name)
		}
	} else if checkType == StructFieldType_Bytes {
		if isList {
			writeStatement = fmt.Sprintf(""+
				"sb.Add(string.Format(\"%s: \\\"{0}\\\"\", "+
				"BitConverter.ToString(this.%s[i])))",
				fieldDef.Name, fieldDef.Name)
		} else {
			writeStatement = fmt.Sprintf(""+
				"sb.Add(string.Format(\"%s: \\\"{0}\\\"\", "+
				"BitConverter.ToString(this.%s)))",
				fieldDef.Name, fieldDef.Name)
		}
	} else if checkType == StructFieldType_Bool {
		if isList {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {0}\", this.%s[i] ? 1 : 0))",
				fieldDef.Name, fieldDef.Name)
		} else {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {0}\", this.%s ? 1 : 0))",
				fieldDef.Name, fieldDef.Name)
		}
	} else if checkType == StructFieldType_Enum {
		if isList {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {0}\", (int)this.%s[i]))",
				fieldDef.Name, fieldDef.Name)
		} else {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {0}\", (int)this.%s))",
				fieldDef.Name, fieldDef.Name)
		}
	} else if checkType == StructFieldType_Struct {
		if isList {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {0}\", this.%s[i].Dump()))",
				fieldDef.Name, fieldDef.Name)
		} else {
			writeStatement = fmt.Sprintf(
				"sb.Add(string.Format(\"%s: {{ {0} }}\", this.%s.Dump()))",
				fieldDef.Name, fieldDef.Name)
		}
	} else {
		writeStatement = ""
	}

	var indent2 string
	if fieldDef.IsOptional {
		indent2 = "            "
	} else {
		indent2 = "        "
	}
	if isList {
		this.writeLineFormat(sb,
			"%s%sfor (int i = 0; i < this.%s.Count; ++i) {",
			indent, indent2, fieldDef.Name)
		this.writeLineFormat(sb,
			"%s%s    %s;",
			indent, indent2, writeStatement)
		this.writeLineFormat(sb,
			"%s%s}",
			indent, indent2)
	} else {
		this.writeLineFormat(sb,
			"%s%s%s;",
			indent, indent2, writeStatement)
	}

	if fieldDef.IsOptional {
		this.writeLineFormat(sb,
			"%s        }",
			indent)
	}
}

func (this *CSharpCodeGenerator) writeOneStructDeclOptionalFunc(
	sb *strings.Builder, structDef *StructDef, indent string) {

	if structDef.OptionalFieldCount <= 0 {
		return
	}

	for _, def := range structDef.Fields {
		if def.IsOptional == false {
			continue
		}

		byteIndex := def.OptionalFieldIndex / 8
		byteMask := fmt.Sprintf("0x%02x", 1<<(def.OptionalFieldIndex%8))

		this.writeEmptyLine(sb)
		this.writeLineFormat(sb,
			"%s    public bool has_%s()",
			indent, def.Name)
		this.writeLineFormat(sb,
			"%s    {",
			indent)
		this.writeLineFormat(sb,
			"%s        return (this._has_bits_[%d] & %s) > 0;",
			indent, byteIndex, byteMask)
		this.writeLineFormat(sb,
			"%s    }",
			indent)

		this.writeEmptyLine(sb)
		this.writeLineFormat(sb,
			"%s    public void set_has_%s()",
			indent, def.Name)
		this.writeLineFormat(sb,
			"%s    {",
			indent)
		this.writeLineFormat(sb,
			"%s        this._has_bits_[%d] |= %s;",
			indent, byteIndex, byteMask)
		this.writeLineFormat(sb,
			"%s    }",
			indent)

		this.writeEmptyLine(sb)
		this.writeLineFormat(sb,
			"%s    public void clear_has_%s()",
			indent, def.Name)
		this.writeLineFormat(sb,
			"%s    {",
			indent)
		this.writeLineFormat(sb,
			"%s        this._has_bits_[%d] &= (~%s & 0xff);",
			indent, byteIndex, byteMask)
		this.writeLineFormat(sb,
			"%s    }",
			indent)

		this.writeEmptyLine(sb)
		this.writeLineFormat(sb,
			"%s    public void set_%s(%s val)",
			indent, def.Name,
			this.getStructFieldCSharpType(def))
		this.writeLineFormat(sb,
			"%s    {",
			indent)
		this.writeLineFormat(sb,
			"%s        set_has_%s();",
			indent, def.Name)
		this.writeLineFormat(sb,
			"%s        this.%s = val;",
			indent, def.Name)
		this.writeLineFormat(sb,
			"%s    }",
			indent)
	}
}

func (this *CSharpCodeGenerator) writeEnumMapDecl(
	sb *strings.Builder, isFirstDecl *bool, indent string) {

	protoDef := this.descriptor.ProtoDef

	for _, def := range protoDef.EnumMaps {
		this.writeOneEnumMapDecl(sb, def, isFirstDecl, indent)
	}
}

func (this *CSharpCodeGenerator) writeOneEnumMapDecl(
	sb *strings.Builder, enumMapDef *EnumMapDef,
	isFirstDecl *bool, indent string) {

	if *isFirstDecl == true {
		*isFirstDecl = false
	} else {
		this.writeEmptyLine(sb)
	}

	this.writeLineFormat(sb,
		"%spublic sealed class %s",
		indent, enumMapDef.Name)
	this.writeLineFormat(sb,
		"%s{",
		indent)

	for _, def := range enumMapDef.Items {
		if def.Type == EnumMapItemType_Default ||
			def.Type == EnumMapItemType_Int {
			this.writeLineFormat(sb,
				"%s    public const int %s = %d;",
				indent, def.Name, def.IntValue)
		} else if def.Type == EnumMapItemType_CurrentEnumRef {
			this.writeLineFormat(sb,
				"%s    public const int %s = %s;",
				indent, def.Name, def.RefEnumItemDef.Name)
		}
	}
	if len(enumMapDef.Items) > 0 {
		this.writeEmptyLine(sb)
	}

	this.writeLineFormat(sb,
		"%s    private static int[] s_id_list_ = {",
		indent)
	for _, def := range enumMapDef.Items {
		if def.RefStructDef == nil {
			continue
		}
		this.writeLineFormat(sb,
			"%s        %s,",
			indent, def.Name)
	}
	this.writeLineFormat(sb,
		"%s    };",
		indent)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    private static BaseStruct.CreateFunc[] s_create_func_list_ = {",
		indent)
	for _, def := range enumMapDef.Items {
		if def.RefStructDef == nil {
			continue
		}
		this.writeLineFormat(sb,
			"%s        %s.Create,",
			indent,
			this.getStructFullQualifiedName(def.RefStructDef))
	}
	this.writeLineFormat(sb,
		"%s    };",
		indent)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    private class Id<T> where T : BaseStruct",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        public static int Value;",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    static %s()",
		indent, enumMapDef.Name)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	for _, def := range enumMapDef.Items {
		if def.RefStructDef == nil {
			continue
		}
		this.writeLineFormat(sb,
			"%s        Id<%s>.Value = %s;",
			indent,
			this.getStructFullQualifiedName(def.RefStructDef),
			def.Name)
	}
	this.writeLineFormat(sb,
		"%s    }",
		indent)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
        "%s    public static int GetId<T>() where T : BaseStruct",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        return Id<T>.Value;",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"%s    public static BaseStruct Create(int id)",
		indent)
	this.writeLineFormat(sb,
		"%s    {",
		indent)
	this.writeLineFormat(sb,
		"%s        int index = Array.BinarySearch(s_id_list_, id);",
		indent)
	this.writeLineFormat(sb,
		"%s        if (index < 0) {",
		indent)
	this.writeLineFormat(sb,
		"%s            return null;",
		indent)
	this.writeLineFormat(sb,
		"%s        } else {",
		indent)
	this.writeLineFormat(sb,
		"%s            return s_create_func_list_[index]();",
		indent)
	this.writeLineFormat(sb,
		"%s        }",
		indent)
	this.writeLineFormat(sb,
		"%s    }",
		indent)

	this.writeLineFormat(sb,
		"%s}",
		indent)
}
