package main

import (
	"path/filepath"
	"strings"
)

type PhpCodeGenerator struct {
	BaseCodeGenerator
}

func NewPhpCodeGenerator() *PhpCodeGenerator {
	newObj := new(PhpCodeGenerator)

	return newObj
}

func (this *PhpCodeGenerator) Close() {
	this.close()
}

func (this *PhpCodeGenerator) Generate(
	descriptor *ProtocolDescriptor,
	outputDir string, newLineType NewLineType) bool {

	this.init(descriptor, newLineType)

	sourceFilePath := filepath.Join(
		outputDir, this.descriptor.ProtoDef.Name+".php")
	sourceFileContent := this.generateSourceFile()
	if utilWriteAllText(sourceFilePath, sourceFileContent) == false {
		return false
	}

	return true
}

func (this *PhpCodeGenerator) generateSourceFile() string {
	var sb strings.Builder

	this.writePhpTagStart(&sb)
	this.writeDontEditComment(&sb)
	this.writeNamespaceDecl(&sb)
	this.writePhpTagEnd(&sb)

	return sb.String()
}

func (this *PhpCodeGenerator) writePhpTagStart(
	sb *strings.Builder) {

	this.writeLine(sb,
		"<?php")
}

func (this *PhpCodeGenerator) writePhpTagEnd(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"/* end of %s.php */",
		protoDef.Name)
}

func (this *PhpCodeGenerator) writeDontEditComment(
	sb *strings.Builder) {

	this.writeLine(sb,
		"/*")
	this.writeLine(sb,
		" * Generated by brickred exchange compiler.")
	this.writeLine(sb,
		" * Do not edit unless you are sure that you know what you are doing.")
	this.writeLine(sb,
		" */")
}

func (this *PhpCodeGenerator) writeNamespaceDecl(
	sb *strings.Builder) {

	protoDef := this.descriptor.ProtoDef

	namespaceDef, ok := protoDef.Namespaces["php"]
	if ok == false {
		return
	}
	namespaceName := strings.Join(namespaceDef.NamespaceParts, "\\")

	this.writeEmptyLine(sb)
	this.writeLineFormat(sb,
		"namespace %s;",
		namespaceName)
}
